"""Renderer protocol; importing it has no GUI dependency."""

from __future__ import annotations

from collections.abc import Callable, Mapping
from typing import Protocol

from psx.core.events import EventSlot
from psx.core.vnode import VNode


class Renderer(Protocol):
    def create(self, node: VNode, parent: object | None) -> object: ...
    def update(self, handle: object, changed: Mapping[str, object], removed: frozenset[str]) -> None: ...
    def insert(self, parent: object, child: object, index: int) -> None: ...
    def move(self, parent: object, child: object, index: int) -> None: ...
    def remove(self, parent: object, child: object) -> None: ...
    def bind_event(self, handle: object, event: str, slot: EventSlot) -> object: ...
    def unbind_event(self, subscription: object) -> None: ...
    def destroy(self, handle: object) -> None: ...
    def schedule_ui(self, callback: Callable[[], None]) -> None: ...
    def run(self) -> int: ...
